# Generated by Django 3.0.4 on 2021-04-02 16:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200418_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=tinymce.models.HTMLField(max_length=255, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Question'),
        ),
    ]
