# Generated by Django 3.0.4 on 2022-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20221121_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(upload_to='anwerimages'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(upload_to='questionimages'),
        ),
    ]
